services:
  excalidraw:
    build: .
    environment:
      - NODE_ENV=production
      - VITE_APP_AI_BACKEND=https://excalidraw-backend.martin-linde.com
      - VITE_APP_BACKEND_V2_GET_URL=https://excalidraw.martin-linde.com
      - VITE_APP_WS_SERVER_URL=wss://excalidraw.martin-linde.com/ws
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.excalidraw.rule=Host(`excalidraw.martin-linde.com`)"
      - "traefik.http.services.excalidraw.loadbalancer.server.port=80"  # Assuming build exposes 80
    networks:
      - excalidraw-net
  excalidraw-room:
    image: excalidraw/excalidraw-room:latest
    environment:
      - PORT=5001
    networks:
      - excalidraw-net
networks:
  excalidraw-net:
    driver: bridge
